### PR TITLE
Remove explicit CLS dependency

### PR DESCRIPTION
**Pull request by hildjj**
As suggested in #70.  People that want to use CLS can take the dependency themselves.

### CODE REVIEW

**Comment by analog-nico** [comment]
Hi @hildjj, a thought I had, too. However, since removing the dependency is a breaking change I would rather work on the upcoming v3 release: It will add ES6 promise support (issues #65 and #71) which most likely will allow the user to inject his preferred promise implementation. With that the CLS support can be configured outside of Request-Promise and `bindCLS` as well as the dependency can be dropped.

Does this sound good to you? The release will take a few weeks but then the breaking changes come with new features. Until then I would keep this PR open so I can merge it before the release.

**Comment by hildjj** [comment]
Version numbers are cheap, but I understand.  I can depend on my fork until you're done.

**Comment by jey** [comment]
:+1:.

Currently, `npm install request-promise` warns:

```
npm WARN EPEERINVALID cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.
```

**Comment by ekryski** [comment]
Ya I'm with @hildjj. Version numbers are cheap. If we can cut a new major release without CLS that would be sweet. :grin:

**Comment by analog-nico** [comment]
Hey guys, I am with you. Indeed, Request-Promise is in a bad state with that. Just give me a few days. I am really busy right now.

**Comment by analog-nico** [comment]
I just published `request-promise@2.0.0` which doesn't depend on `cls-bluebird` anymore and thus also doesn't fail `npm shrinkwrap` anymore. Thanks @hildjj for the PR!

**Comment by ekryski** [comment]
Woot! Thanks @analog-nico!

**Comment by analog-nico** [comment]
Hi buddies, I just releases `request-promise@4.0.0` which doesn't call `require('cls-bluebird')` at all anymore. That means that you may now remove any workarounds – e.g. for your resource bundler – you may still have in place.

**Pull request merged**
