### PR TITLE
Changed versioning system in package.json to caret based instead of fixed

### PR DESCRIPTION
**Pull request by tarungarg546**
Hi there,

I see that in your package.json , versioning of dependencies required were inconsistent some are used with preferred "^"(Caret) based semantic versioning and some were fixed based . So in ther PR i changed whole versioning system to  Caret based (^).

So what's the advantage we'll get from changing it to Caret based . Well if you see [npm docs](https://docs.npmjs.com/cli/update). 

They clearly states that by using fixed dependencies version when there is new version available for that package. 
`npm outdated` would show something like 
image

As you can see latest version is greater and considered to be feature update/rich that old veriosn. Now as we are using fixed versioning our 'Wanted' column in above image shows what our fixed version is. Now even if we try to update those by using `npm update` they wont update because Wanted and Current version are same.

Now if change it to "^" bases versioning we would see result of `npm outdated` like below :-
image

Now as you can see wanted and current differs now and if we now run `npm update` it will actually update our package to latest version wanted.

Now to handle major changes like that happened when express moved from 3.x.x to 4.x.x  and everything used in express 3.x.x wont work in 4.x.x ; npm does a trick that when using caret based system it only updates your package if from major.minor.patch , minor / patch differs in wanted and current version. If we use "~" based versioning then it will check for patch only and it will check none in case of fixed versioning.

If there is major version update it wont update it . you have to do it manually. So this way i see no reason why we should not use Caret based versioning and try to be consistent.
Please ignore any typos or grammatical errors.
Thanks & Regards,
Tarun Garg

### CODE REVIEW

**Comment by analog-nico** [comment]
Hi Tarun, this is actually intentional. Those libs using the "x" are part of the test environment. I don't want the test environment to fail because of accidentally introduced breaking changes. Thus I use the "x" to minimise chance to run these annoyances. I prefer to update the versions from time to time manually. Since it is just the test environment it doesn't need to be always up-to-date. However, the two libraries which use the caret are actually libraries that are used in the tests for the cls support. Think of them more like peer dependencies. So those should always be up-to-date.

**Comment by tarungarg546** [comment]
Hi analog-nico,

As i said breaking change is generally in major version [ as happened with express ] not any minor or patch.

Also if there is some breaking change due to mistake of someone so that could happen in patch also  ... So in that case better use fixed versioning instead of using "x".

**Comment by analog-nico** [comment]
You are right. If I'd be really paranoid fixed versioning plus `npm shrinkwrap` would be the way to go. I am just assuming everyone tries to follow semver as best as they can and it is most likely to introduce breaking changes by accident when adding new features. Anyway, it is rather a personal choice which works well for me...

**Comment by tarungarg546** [comment]
Okay so what i can gather is it's just a matter of personal choice but you will try to stick with "x" type method of versioning for now.
Correct me if i am wrong.

**Comment by analog-nico** [comment]
Yes, I'll keep the x's. I mean fixed version would be fine, too. But carets are too loose. Just from experience I prefer that the CI build most likely fails because of the code - not the test environment. Reduces annoyances and speeds up debugging. I rather intentionally make a seperate build in which I only update the test environment.

**Comment by tarungarg546** [comment]
Cool sounds good :+1: 
BTW any reason of not having something like rp.all() as Promise.all()

**Pull request closed without merging**
