### PR TITLE
Require just used functions & use natives

### PR DESCRIPTION
**Pull request by luanmuniz**
Hi,

I made this because after a few requests using this module, lodash was causing some memory allocation problems, the full file is very big and it was causing me problems.

I don't quite understand why, but make just these changes, requiring just the used functions and using a few native functions, my application decrease the memory allocation from 500mb to 220mb.

### CODE REVIEW

**Comment by analog-nico** [comment]
Thanks @luanmuniz !

That is an important finding I would like to understand better so that future versions don't reintroduce this issue. Can you say something about the following questions?

1. The code pieces you replaced with native functions are only executed once when you require the module. I expect if you revert them to using lodash functions you still won't have the memory issue. Could you try this out?
2. Apart from the native functions you did (1) require individual lodash functions and (2) update lodash from 3.6.x to ^3.6.0. First of all, which lodash version do you use? Please have a look at `/node_modules/request-promise/node_modules/lodash/package.json`. This may answer whether (1) or (2) resolved the issue.

**Comment by luanmuniz** [comment]
1. Yes. When the native is replaced for the lodash version the memory issues its not there. The problem is in calling the entire module for just a few functions. (Full lodash has almost 500kb)
2. The 1 is the one that solve the issue. `request-promise` is using 3.6 right now. I meant to update to 3.10 just to update, not to solve the problem (My mistake pushing just a different call for the same version)
2.1 Update to 3.10 is a good thing because there are a lot of modules using lodash and most of then use the last version and when you have 2 or more versions at the same application (different dependences using different versions) node.js need to cache all the versions instead of just one.

Do you want me to update the PR in any way?

**Comment by analog-nico** [comment]
Thanks for the info @luanmuniz ! I can take it from here. You don't need to update the PR.

**Comment by analog-nico** [comment]
I just published version 0.4.3 on NPM which contains your changes. Thanks for your contribution!

**Comment by luanmuniz** [comment]
Thank you very much! :D

**Comment by luanmuniz** [comment]
Just by curiosity, is there a reason not to use the native `Object.keys`, `Array.forEach` and the `isUndefined`?

**Comment by analog-nico** [comment]
I don't know. I leave the expertise on subtle differences between platforms to lodash. ;)

**Pull request merged**
